### ISSUE TITLE
Can't see icons

### ISSUE THREAD

**Issue by echads** [ReactUnity/samples#1]
Hi, great project!

I wanted to drop a note letting you know I can not see the icons in the Unity Editor.

![image](https://user-images.githubusercontent.com/37284476/152586710-2668813a-5614-4aeb-8242-a7662a2d3c38.png)

I tried a few different points in the repo and was never able to get them to show up. Tried a few different versions of the package too.

When it does work, how do we hook into it to display a characters inventory. Does it read  a JSON file in a save folder or something?
[EDIT]
Found this. https://github.com/ReactUnity/core/wiki/Communication-between-Unity-and-React

**Comment by echads** [comment]
Digging into the Hierarchy I can see a few icons, looks like they are covered up or something?
![image](https://user-images.githubusercontent.com/37284476/152587620-d4f6a370-5003-4748-9a27-14838b44dff3.png)

**Comment by gkurt** [comment]
Updated the main branch. I haven't touched this sample in a while so it may be out of date. There will be more samples when I have time, but for now only `2 - RPG` should be working.

Don't forget to `yarn install` after getting the new changes!
